### ISSUE TITLE
Demo project does not compile

### ISSUE THREAD

**Issue by JensMertelmeyer** [thatlr/Delphi-StackTrace#1]
1. `{$include CompilerOptions.inc}` has to be commented out because the file is not included
2. `uses WinMemMgr` has to be commented out because the file is not included
3. `uses MemTest` has to be commented out because the file is not included
4. `uses CorrectLocale` has to be commented out because the file is not included
5. The .dproj file is missing and therefore the following properties are not set:
  a.  Use `.\..\source\` and `.\..\source\windows\` as search path
  b. Compile as a console application
  c. Enable detailed map file
  d. Post-Build event

**Comment by thatlr** [comment]
Yes, I have much more own library units than I'm willing go post here, including an Memory Manager replacement (as the built-in one fragments address space too much) and a Memory validator (including allocations made by COM).
As for the dproj file: Delphi 2009 and 10.1 do not work well with the same dproj. D2009 sometimes gets confused with some msbuild things inside the dproj or otherwise, and D10 has problems with adding the 64bit part to a D2009 dproj and inheritance of options (for example, enabling the IDE debugging can cost you hours). So just create one yourself.

**Comment by thatlr** [comment]
Please also see my comment to the other issue (as not being intended to be a stand-alone "project" in the first place).
