### ISSUE TITLE
add a line in dpr

### ISSUE THREAD

**Issue by limelect** [thatlr/Delphi-StackTrace#2]
D10.2.3
add
{$APPTYPE CONSOLE}
other wise writln dose not work

**Comment by thatlr** [comment]
Acknowledged. But this would screw up the line numbers from the screenshots :-) 

More or less, I put this "demo" .dpr only here to enable you to compare this source against the screenshots, not so much as something you should compile yourself stand-alone.
Everyone has its own setup of unit search pathes, and I would expect that you put StackTrace.pas inside one of your own library directories, so that it can be found when you are compiling it into your own projects.
